server:
  port: ${${spring.application.name}.port}
  
spring:
  application:
    name: '@project.artifactId@'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ankit320422/spring-cloud.git
          skip-ssl-validation: true
  profiles:
    include: common