appVersion: '20210508-1927'





cloud-config-server:
  port: 8888
  
currency-exchange-service:
  port: 8081
  
  
limit-services:
  port: 8082

  
spring:  jpa:    show-sql: true  datasource:    url: jdbc:h2:mem:testdb  h2:    console:      enabled: true