
server:
  port: ${${spring.application.name}.port}
limit-service:
  max: 97
  min: 23
spring:
  application:
    name: 'currency-exchange-service'
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    include: common
